[2025-05-18T07:23:48.271+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-18T07:23:48.295+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: vietnamnet_crawler_24h.crawl_doi-song manual__2025-05-18T07:04:55.090365+00:00 [queued]>
[2025-05-18T07:23:48.307+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: vietnamnet_crawler_24h.crawl_doi-song manual__2025-05-18T07:04:55.090365+00:00 [queued]>
[2025-05-18T07:23:48.311+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-05-18T07:23:48.389+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): crawl_doi-song> on 2025-05-18 07:04:55.090365+00:00
[2025-05-18T07:23:48.397+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=12762) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-18T07:23:48.398+0000] {standard_task_runner.py:63} INFO - Started process 12763 to run task
[2025-05-18T07:23:48.399+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'vietnamnet_crawler_24h', 'crawl_doi-song', 'manual__2025-05-18T07:04:55.090365+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/dags.py', '--cfg-path', '/tmp/tmpcteb5xz4']
[2025-05-18T07:23:48.401+0000] {standard_task_runner.py:91} INFO - Job 40: Subtask crawl_doi-song
[2025-05-18T07:23:48.539+0000] {task_command.py:426} INFO - Running <TaskInstance: vietnamnet_crawler_24h.crawl_doi-song manual__2025-05-18T07:04:55.090365+00:00 [running]> on host fa0f5fb7e7ff
[2025-05-18T07:23:48.758+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='vietnamnet_crawler_24h' AIRFLOW_CTX_TASK_ID='crawl_doi-song' AIRFLOW_CTX_EXECUTION_DATE='2025-05-18T07:04:55.090365+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-18T07:04:55.090365+00:00'
[2025-05-18T07:23:48.759+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-18T07:23:49.027+0000] {crawler.py:55} INFO - Đã kết nối thành công với MongoDB: News
[2025-05-18T07:23:50.157+0000] {logging_mixin.py:188} INFO - [INIT].... → Crawl4AI 0.6.3
[2025-05-18T07:23:57.744+0000] {logging_mixin.py:188} INFO - [FETCH]... ↓ https://vietnamnet.vn/tin-tuc-24h?bydaterang=&cate=000007          
| ✓ | ⏱: 7.34s
[2025-05-18T07:23:58.595+0000] {local_task_job_runner.py:310} WARNING - State of this instance has been externally set to success. Terminating instance.
[2025-05-18T07:23:58.602+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-05-18T07:23:58.610+0000] {process_utils.py:132} INFO - Sending 15 to group 12763. PIDs of all processes in the group: [12768, 12783, 12790, 12791, 12813, 12819, 12850, 12851, 12873, 12890, 12812, 12763]
[2025-05-18T07:23:58.611+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 12763
[2025-05-18T07:23:58.612+0000] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-05-18T07:23:58.802+0000] {logging_mixin.py:188} INFO - [SCRAPE].. ◆ https://vietnamnet.vn/tin-tuc-24h?bydaterang=&cate=000007          
| ✓ | ⏱: 0.86s 
[ERROR]... × Error closing context: BrowserContext.close: Target page, context 
or browser has been closed
[2025-05-18T07:23:58.945+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=12850, status='terminated', started='07:23:50') (12850) terminated with exit code None
[2025-05-18T07:23:58.967+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=12783, status='terminated', started='07:23:49') (12783) terminated with exit code None
[2025-05-18T07:23:58.977+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=12851, status='terminated', started='07:23:50') (12851) terminated with exit code None
[2025-05-18T07:23:58.990+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=12790, status='terminated', started='07:23:49') (12790) terminated with exit code None
[2025-05-18T07:23:58.992+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=12812, status='terminated', started='07:23:49') (12812) terminated with exit code None
[2025-05-18T07:23:59.003+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=12791, status='terminated', started='07:23:49') (12791) terminated with exit code None
[2025-05-18T07:23:59.005+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=12819, status='terminated', started='07:23:49') (12819) terminated with exit code None
[2025-05-18T07:23:59.011+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=12890, status='terminated', started='07:23:55') (12890) terminated with exit code None
[2025-05-18T07:23:59.013+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=12873, status='terminated', started='07:23:52') (12873) terminated with exit code None
[2025-05-18T07:23:59.031+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-18T07:23:59.032+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=12813, status='terminated', started='07:23:49') (12813) terminated with exit code None
[2025-05-18T07:23:59.178+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=12763, status='terminated', exitcode=0, started='07:23:47') (12763) terminated with exit code 0
[2025-05-18T07:23:59.180+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=12768, status='terminated', started='07:23:48') (12768) terminated with exit code None
