[2025-05-18T07:23:31.299+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-18T07:23:31.381+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: vietnamnet_crawler_24h.crawl_the-gioi manual__2025-05-18T07:04:55.090365+00:00 [queued]>
[2025-05-18T07:23:31.412+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: vietnamnet_crawler_24h.crawl_the-gioi manual__2025-05-18T07:04:55.090365+00:00 [queued]>
[2025-05-18T07:23:31.415+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-05-18T07:23:31.453+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): crawl_the-gioi> on 2025-05-18 07:04:55.090365+00:00
[2025-05-18T07:23:31.465+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=12149) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-18T07:23:31.469+0000] {standard_task_runner.py:63} INFO - Started process 12268 to run task
[2025-05-18T07:23:31.473+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'vietnamnet_crawler_24h', 'crawl_the-gioi', 'manual__2025-05-18T07:04:55.090365+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/dags.py', '--cfg-path', '/tmp/tmplm8iabdc']
[2025-05-18T07:23:31.477+0000] {standard_task_runner.py:91} INFO - Job 39: Subtask crawl_the-gioi
[2025-05-18T07:23:31.550+0000] {task_command.py:426} INFO - Running <TaskInstance: vietnamnet_crawler_24h.crawl_the-gioi manual__2025-05-18T07:04:55.090365+00:00 [running]> on host fa0f5fb7e7ff
[2025-05-18T07:23:31.742+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='vietnamnet_crawler_24h' AIRFLOW_CTX_TASK_ID='crawl_the-gioi' AIRFLOW_CTX_EXECUTION_DATE='2025-05-18T07:04:55.090365+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-18T07:04:55.090365+00:00'
[2025-05-18T07:23:31.746+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-18T07:23:32.143+0000] {crawler.py:55} INFO - Đã kết nối thành công với MongoDB: News
[2025-05-18T07:23:33.468+0000] {logging_mixin.py:188} INFO - [INIT].... → Crawl4AI 0.6.3
[2025-05-18T07:23:37.725+0000] {logging_mixin.py:188} INFO - [FETCH]... ↓ https://vietnamnet.vn/tin-tuc-24h?bydaterang=&cate=000005          
| ✓ | ⏱: 4.14s
[2025-05-18T07:23:38.073+0000] {logging_mixin.py:188} INFO - [SCRAPE].. ◆ https://vietnamnet.vn/tin-tuc-24h?bydaterang=&cate=000005          
| ✓ | ⏱: 0.34s
[2025-05-18T07:23:38.077+0000] {logging_mixin.py:188} INFO - [COMPLETE] ● https://vietnamnet.vn/tin-tuc-24h?bydaterang=&cate=000005          
| ✓ | ⏱: 4.50s
[2025-05-18T07:23:38.431+0000] {crawler.py:85} INFO - Tìm thấy 25 link bài viết cho danh mục the-gioi
[2025-05-18T07:23:39.114+0000] {crawler.py:110} INFO - Đã lọc: 25 URLs ban đầu -> 25 URLs sau xử lý live
[2025-05-18T07:23:39.115+0000] {crawler.py:255} INFO - Đang crawl 25 bài viết mới từ danh mục the-gioi...
[2025-05-18T07:23:39.115+0000] {crawler.py:258} INFO - --> Crawl: https://vietnamnet.vn/ukraine-cong-bo-ton-that-cua-nga-dung-uav-pha-kho-dan-o-crum-2402159.html
[2025-05-18T07:23:40.191+0000] {logging_mixin.py:188} INFO - [INIT].... → Crawl4AI 0.6.3
[2025-05-18T07:23:45.430+0000] {logging_mixin.py:188} INFO - [FETCH]... ↓ 
https://vietnamnet.vn/ukraine-cong-bo-ton-that-cua-nga-dung-uav-pha-kho-dan-o-cr
um-2402159.html      | ✓ | ⏱: 5.08s
[2025-05-18T07:23:45.670+0000] {logging_mixin.py:188} INFO - [SCRAPE].. ◆ 
https://vietnamnet.vn/ukraine-cong-bo-ton-that-cua-nga-dung-uav-pha-kho-dan-o-cr
um-2402159.html      | ✓ | ⏱: 0.24s
[2025-05-18T07:23:45.672+0000] {logging_mixin.py:188} INFO - [COMPLETE] ● 
https://vietnamnet.vn/ukraine-cong-bo-ton-that-cua-nga-dung-uav-pha-kho-dan-o-cr
um-2402159.html      | ✓ | ⏱: 5.32s
[2025-05-18T07:23:46.870+0000] {local_task_job_runner.py:310} WARNING - State of this instance has been externally set to success. Terminating instance.
[2025-05-18T07:23:46.872+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-05-18T07:23:46.878+0000] {process_utils.py:132} INFO - Sending 15 to group 12268. PIDs of all processes in the group: [12567, 12586, 12591, 12594, 12268]
[2025-05-18T07:23:46.879+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 12268
[2025-05-18T07:23:46.880+0000] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-05-18T07:23:46.881+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-18T07:23:47.186+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=12268, status='terminated', exitcode=0, started='07:23:30') (12268) terminated with exit code 0
[2025-05-18T07:23:47.188+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=12591, status='terminated', started='07:23:39') (12591) terminated with exit code None
[2025-05-18T07:23:47.188+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=12586, status='terminated', started='07:23:39') (12586) terminated with exit code None
[2025-05-18T07:23:47.189+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=12594, status='terminated', started='07:23:39') (12594) terminated with exit code None
[2025-05-18T07:23:47.190+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=12567, status='terminated', started='07:23:38') (12567) terminated with exit code None
