[2025-06-22T16:51:40.942+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-22T16:51:40.960+0000] {taskinstance.py:2066} INFO - Dependencies not met for <TaskInstance: deepai_crawler_10min.crawl_hardware scheduled__2025-06-22T10:40:00+00:00 [success]>, dependency 'Task Instance State' FAILED: Task is in the 'success' state.
[2025-06-22T16:51:40.963+0000] {local_task_job_runner.py:163} INFO - Task is not able to be run
